DROP TABLE IF EXISTS tweets CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL, 
  name VARCHAR(255) NOT NULL,
  handle VARCHAR(255) NOT NULL, 
  avatar VARCHAR(255) NOT NULL);

CREATE TABLE tweets (
  id SERIAL PRIMARY KEY NOT NULL, 
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tweet_text TEXT NOT NULL,
  date_posted TIMESTAMPTZ NOT NULL,
);