DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tweets CASCADE;
DROP TABLE IF EXISTS retweets CASCADE;
DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY NOT NULL, 
  name VARCHAR(255) NOT NULL,
  handle VARCHAR(255) NOT NULL, 
  avatar VARCHAR(255) NOT NULL
  );

CREATE TABLE tweets (
  id SERIAL PRIMARY KEY NOT NULL, 
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tweet_text TEXT NOT NULL,
  date_posted TIMESTAMPTZ NOT NULL
);

CREATE TABLE likes(
  id SERIAL PRIMARY KEY NOT NULL, 
  tweet_id INTEGER REFERENCES tweets(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  unique (tweet_id, user_id)
);

CREATE TABLE retweets(
  id SERIAL PRIMARY KEY NOT NULL, 
  tweet_id INTEGER REFERENCES tweets(id) ON DELETE CASCADE,
  retweeter_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ,
  unique(retweeter_id, tweet_id)
);